apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: hs-frontend
  labels:
    app: hs-frontend
spec:
  selector:
    matchLabels:
      app: hs-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: hs-frontend                                  # 6
    spec:
      containers:
        - image: ykpgrr/hate-speech-detection-frontend
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80
