apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-ml
  labels:
    app: hs-ml
spec:
  selector:
     matchLabels:
       app: hs-ml
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: hs-ml
    spec:
      containers:
        - image: ykpgrr/hate-speech-detection-ml-service
          imagePullPolicy: Always
          name: hs-ml
          ports:
            - containerPort: 5000
